version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time-tracker
      PGDATA: /data/postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    # expose:
    #   - "5432"

  time-tracker:
    image: time-tracker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/app/config.yml
      - ./.env:/app/.env # TODO: remove in the future
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: unless-stopped

  enrich-user-data:
    image: enrich-user-data
    build:
      context: enrich_user_data_service_mock
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    restart: unless-stopped
